# Generated by Django 6.0.2 on 2026-02-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FLEET_MANAGER', 'Fleet Manager'), ('DISPATCHER', 'Dispatcher'), ('SAFETY_OFFICER', 'Safety Officer'), ('FINANCIAL_ANALYST', 'Financial Analyst')], db_index=True, default='FLEET_MANAGER', max_length=20),
        ),
    ]
