# Generated by Django 6.0.2 on 2026-02-21 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('BIKE', 'Bike')], db_index=True, max_length=20)),
                ('max_capacity', models.DecimalField(decimal_places=2, help_text='Maximum cargo capacity in kg', max_digits=10)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Initial purchase cost', max_digits=12)),
                ('odometer_current', models.PositiveIntegerField()),
                ('is_retired', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='priority',
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status', 'created_at'], name='workflow_wo_status_54100a_idx'),
        ),
    ]
