# Generated by Django 6.0.2 on 2026-02-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='cargo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargo weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='workflow.driver'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='end_odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='start_odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='workflow.vehicle'),
        ),
    ]
