# Generated by Django 6.0.2 on 2026-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maintenance cost', max_digits=12),
            preserve_default=False,
        ),
    ]
