# Generated by Django 6.0.2 on 2026-02-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_maintenancelog_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.DecimalField(decimal_places=2, help_text='Fuel quantity in liters', max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Fuel cost', max_digits=12)),
                ('odometer_reading', models.PositiveIntegerField(help_text='Vehicle odometer at time of refueling')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='workflow.workitem')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='workflow.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='workflow_fu_vehicle_cd7d94_idx')],
            },
        ),
    ]
