# Generated by Django 6.0.2 on 2026-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_fuellog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_retired',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_SHOP', 'In Shop'), ('RETIRED', 'Retired')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
