# Generated by Django 6.0.2 on 2026-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_remove_vehicle_is_retired_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='estimated_fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
